<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('8', '/uploads/allimg/161227/1-16122G14532493.jpg');
$maNum = 1;
$myaddons[$maNum] = array('9', '/uploads/allimg/161227/1-16122G14543625.jpg');
$maNum = 2;
$myaddons[$maNum] = array('10', '/uploads/allimg/161227/1-16122G14553439.jpg');
$maNum = 3;
$myaddons[$maNum] = array('11', '/uploads/allimg/161227/1-16122G14605296.jpg');
$maNum = 4;
