{dede:field name='keywords'}HTM2-SWD断电延时继电器上线{/dede:field}
{dede:field name='description'}产品概述1、极小的体积，欧规18mm模数化外壳，35mm导轨安装，极大提高安装密度，节省空间，不用开孔，一把螺丝刀10秒完成安装。2、国际最先进电源电路，极低的功耗，极宽的工作电压（24-690V AC/DC通用），节能环保。性能比肩ABB、施耐德、西门子等国际知名企{/dede:field}
{dede:field name='title'}HTM2-SWD断电延时继电器上线_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
