<div class="margin-large-bottom not-animated"  data-animate="slideInUp" data-delay="200">
              <div class="item item1">
                <div class="media-img"><a href="[field:arcurl/]" title="[field:title/]" class="artzoomimgs" style="background-image:url([field:picname/])"></a></div>
                <div class="content">
                  <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
                  <span class='time'>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                  <div class="desc">[field:description function="cn_substr(@me,160)"/]...</div>
                </div>
              </div>
            </div>