<?php
$z[0]=Array("noteinfo","",0,156);
$z[0][4]['notename']="技术文档";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<!-- 案例 -->{/dede:areastart}\r\n    {dede:areaend}<ul class=\"fen\">\r\n				<span class=\"page-disabled\">&laquo; 首页</span><span class=\"page-disabled control\">&#8249; 前一页</span><span class=\"page-num page-cur background fontcolor\">1</span><a class=\"page-num\" href=\"/case-1027-2.html\">2</a><a class=\"control\" href=\"/case-1027-2.html\">下一页 &#8250;</a><a href=\"/case-1027-2.html\">末页 &raquo;</a>\r\n		</ul>{/dede:areaend}\r\n",160,930);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://www.humcore.com/case-1027-(*).html";
$z[1][4]['startid']="1";
$z[1][4]['endid']="2";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']=".html";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>