{dede:field name='keywords'}悍客电气HTM2-SWE.22通电脉冲延{/dede:field}
{dede:field name='description'}HTM2-SWE.22时间继电器是悍客电气（上海）有限公司自主研发的通电延时OFF类电子时间继电器，拥有自主知识产权，外观与性能比肩ABB、西门子、施耐德等国际品牌企业；是进口时间继电器理想的替代产品！{/dede:field}
{dede:field name='title'}悍客电气HTM2-SWE.22通电脉冲延时时间继电器上线_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
