{dede:field name='keywords'}箱变测控一体化装置,电压电流相{/dede:field}
{dede:field name='description'}客电气（上海）有限公司，主要从事箱变测控一体化装置,电压电流相序时间继电器的研发与生产，更多说情请查看www.humcore.com。{/dede:field}
{dede:field name='title'}悍客电气（上海）有限公司网站上线_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
