{dede:field name='keywords'}分合闸监视继电器的特点、应用及{/dede:field}
{dede:field name='description'}跳合位监视继电器应具备如下特点：1、极小的工作电流（不大于5mA）2、极宽的工作电压（因为是串联，操作电源电压会被跳合闸线圈或防跳继电器线圈分压，造成实际加在跳合位监视继电器线圈上的电压低于操作电压，具体根据分压线圈内阻决定）。{/dede:field}
{dede:field name='title'}分合闸监视继电器的特点、应用及选型_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
