{dede:field name='keywords'}悍客电气HTM2-SWG.21带辅源断电{/dede:field}
{dede:field name='description'}HTM2-SWG.21时间继电器是悍客电气（上海）有限公司自主研发的带瞬动触点的有辅源断电延时时间继电器，其外形与性能比肩ABB、西门子、施耐德等国际品牌企业；是理想的进口继电器替代产品！{/dede:field}
{dede:field name='title'}悍客电气HTM2-SWG.21带辅源断电延时时间继电器上线_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
