{dede:field name='keywords'}ARC700-F风电箱变测控装置上线{/dede:field}
{dede:field name='description'}ARC700-F风电箱变测控装置是悍客电气（上海）有限公司研发生产的新一代风电场升压箱变智能测控装置，该装置集保护、测量、控制、通信管理、自愈光纤环网（网络交换）为一体，极大的简化了设计方案，为用户节约了投资成本和维护成本，比老式方案节省三分之二网{/dede:field}
{dede:field name='title'}ARC700-F风电箱变测控装置上线_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
