{dede:field name='keywords'}悍客电气HTM2-SWG.12信号断开延{/dede:field}
{dede:field name='description'}HTM2-SWG.12时间继电器是悍客电气（上海）自主研发的信号断开延时（带辅源断电延时）时间继电器，外形与性能比肩ABB、施耐德、西门子等国际品牌企业产品；是进口时间继电器理想替代产品！{/dede:field}
{dede:field name='title'}悍客电气HTM2-SWG.12信号断开延时时间继电器上线_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
