<?php
$z[0]=Array("field","HTR2-EWH.12小电流启动监视继电",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","HTR2-EWH.12小电流启动监视继电器是悍客电气（上海）有限公司研制的新一代跳位合位监视继电器，欧美标准，极小体积，外观性能比肩 ABB、西门子、施耐德等国际品牌企业产品！是最先进的跳合位监视继电器。",72,305);
$z[1][4]['name']="description";
$z[2]=Array("field","HTR2-EWH.12小电流启动监视继电器上线_悍客电气（上海）有限公司",307,405);
$z[2][4]['name']="title";
$z[3]=Array("field","",407,446);
$z[3][4]['name']="writer";
$z[4]=Array("field","",448,487);
$z[4][4]['name']="source";
$z[5]=Array("field","",489,526);
$z[5][4]['name']="body";
$z[6]=Array("field","",528,568);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",570,609);
$z[7][4]['name']="litpic";

?>