<?php
$z[0]=Array("field","HTM2-SWD.12断电延时继电器上线",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","产品概述1、极小的体积，欧规18mm模数化外壳，35mm导轨安装，极大提高安装密度，节省空间，不用开孔，一把螺丝刀10秒完成安装。2、国际最先进电源电路，极低的功耗，极宽的工作电压（24-690V AC/DC通用），节能环保。性能比肩ABB、施耐德、西门子等国际知名企",72,356);
$z[1][4]['name']="description";
$z[2]=Array("field","HTM2-SWD.12断电延时继电器上线_悍客电气（上海）有限公司",358,450);
$z[2][4]['name']="title";
$z[3]=Array("field","",452,491);
$z[3][4]['name']="writer";
$z[4]=Array("field","",493,532);
$z[4][4]['name']="source";
$z[5]=Array("field","",534,571);
$z[5][4]['name']="body";
$z[6]=Array("field","",573,613);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",615,654);
$z[7][4]['name']="litpic";

?>