{dede:field name='keywords'}箱变测控产品新闻,继电器产品新{/dede:field}
{dede:field name='description'}在这里您可以了解到相关箱变测控产品新闻，继电器产品新闻，悍客产品的新闻，详情查阅悍客电气（上海）有限公司官网www.humcore.com;{/dede:field}
{dede:field name='title'}行业新闻_新闻中心_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
