{dede:field name='keywords'}悍客电气HTM2-SWG.22断电延时带{/dede:field}
{dede:field name='description'}HTM2-SWG.22时间继电器是悍客电气（上海）有限公司自主研制的欧规小型化带辅源断电延时继电器，外观与性能比肩ABB、西门子、施耐德等国际品牌企业；是进口时间继电器的理想替代产品！{/dede:field}
{dede:field name='title'}悍客电气HTM2-SWG.22断电延时带辅源时间继电器上线_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
