
<field:name itemname="您的姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="您的手机号" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:email itemname="您的邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:note itemname="备注" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:note>
