<?php
$z[0]=Array("arcurl","",81,96);
$z[1]=Array("picname","",124,140);
$z[2]=Array("arcurl","",242,257);
$z[3]=Array("title","",260,274);
$z[4]=Array("source","",338,353);
$z[5]=Array("writer","",372,387);
$z[6]=Array("pubdate","",407,454);
$z[6][4]['function']="MyDate('Y-m-d',@me)";
$z[7]=Array("description","",506,556);
$z[7][4]['function']="cn_substr(@me,300)";
$z[8]=Array("arcurl","",614,629);

?>