<li class="">
          <dl>
            <dt> <a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></dt>
            <dd>[field:description function='cn_substr(@me,158)'/]¡­¡­ <a href="[field:arcurl/]" title="ÏêÏ¸" target="_blank">[ÏêÏ¸]</a></dd>
          </dl>
          <span><b>[field:pubdate function="MyDate('d',@me)"/]</b>[field:pubdate function="MyDate('y-m',@me)"/]</span> </li>