{dede:field name='keywords'}悍客电气HTM2-SWE.12间隔延时时{/dede:field}
{dede:field name='description'}HTM2-SWE.12时间继电器是悍客电气（上海）有限公司自主研发的一款有自主知识产权的通电脉冲延时继电器，外观性能比肩ABB、施耐德、西门子等国际品牌企业，是理想的进口电子时间继电器替代产品！{/dede:field}
{dede:field name='title'}悍客电气HTM2-SWE.12间隔延时时间继电器上线_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
