{dede:noteinfo notename="行业新闻" channelid="1" macthtype="string"
refurl="http://www.humcore.com/article-item-385.html" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.humcore.com/article-item-(*).html"
startid="257" endid="385" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="newsshow">{/dede:areastart}
    {dede:areaend}<!--Relevant-->{/dede:areaend}
{/dede:listrule}
