{dede:field name='keywords'}HTR2-EWH.22小电流启动监视继电{/dede:field}
{dede:field name='description'}HTR2-EWH.22小电流启动监视继电器就悍客电气（上海）有限公司研制的新一代跳闸合闸回路监视继电器，采用欧规标准，外形性能比肩ABB、西门子、施耐德等国际品牌企业产品，具有极小的体积，极低功耗，极宽电压，节能环保，是最新小型化技术的代表！{/dede:field}
{dede:field name='title'}HTR2-EWH.22小电流启动监视继电器上线{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p class="MsoNormal">
	悍客电气HTR2-EWH.22<span style="font-family:宋体;">小电流启动监视继电器</span><o:p></o:p>
</p>
<p class="MsoNormal">
	<!--[if !supportLists]-->一、<!--[endif]-->基本信息<o:p></o:p>
</p>
<p class="MsoNormal">
	<span style="font-family:宋体;">产品名称：</span>HTR2<span style="font-family:宋体;">系列欧规模数化监视继电器</span><o:p></o:p>
</p>
<p class="MsoNormal">
	<span style="font-family:宋体;">产品型号：</span>HTR2-EWH.22<o:p></o:p>
</p>
<p class="MsoNormal">
	<span style="font-family:宋体;">控制电压：</span>① <span style="font-family:Calibri;">100-460V AC/DC &nbsp;50/60HZ</span><span style="font-family:宋体;">或</span><span style="font-family:Calibri;">DC</span><o:p></o:p>
</p>
<p class="MsoNormal">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;② <span style="font-family:Calibri;">160-690V AC/DC &nbsp;50/60HZ</span><span style="font-family:宋体;">或</span><span style="font-family:Calibri;">DC</span><o:p></o:p>
</p>
<p class="MsoNormal">
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-family:宋体;">二选一</span><o:p></o:p>
</p>
<p class="MsoNormal">
	<span style="font-family:宋体;">转换触点：两付转换接点（</span>6A<span style="font-family:宋体;">）</span><o:p></o:p>
</p>
<p class="MsoNormal">
	工作模式：瞬时动作<o:p></o:p>
</p>
<p class="MsoNormal">
	<span style="font-family:宋体;">模数规格：</span>18mm<o:p></o:p>
</p>
<p class="MsoNormal">
	<!--[if !supportLists]-->二、<!--[endif]-->产品特点<o:p></o:p>
</p>
<p class="MsoNormal">
	<!--[if !supportLists]-->1、<!--[endif]--><span style="font-family:宋体;">极宽的电压输入范围：该产品适应从</span>100-690V<span style="font-family:宋体;">的交直流输入。</span><o:p></o:p>
</p>
<p class="MsoNormal">
	<!--[if !supportLists]-->2、<!--[endif]--><span style="font-family:宋体;">极小的功耗：该产品在任一点动作时功耗不大于</span>0.5W<span style="font-family:宋体;">或</span><span style="font-family:Calibri;">1VA</span><span style="font-family:宋体;">。</span><o:p></o:p>
</p>
<p class="MsoNormal">
	<!--[if !supportLists]-->3、<!--[endif]--><span style="font-family:宋体;">极小的安装体积：仅</span>18mm<span style="font-family:宋体;">宽度，符合欧规标准。</span><o:p></o:p>
</p>
<p class="MsoNormal">
	<span style="font-family:宋体;">了解产品信息请关注我们或联系我们</span>
</p>
<p class="MsoNormal">
	<span style="font-family:宋体;"><br />
</span>
</p>
<p class="MsoNormal">
	<span style="font-family:宋体;"><span style="font-size:16px;"><strong>更多相关文章</strong>：</span></span>
</p>
<p class="MsoNormal">
	<span style="font-family:宋体;"><span style="font-size:16px;"></span></span>
</p>
<p class="MsoNormal">
	<span style="font-family:宋体;"><span style="font-size:16px;"></span></span>
</p>
<p class="MsoNormal">
	<span style="font-family:宋体;"><span style="font-size:16px;"></span><br />
</span>
</p>
<p class="MsoNormal">
	<span style="font-family:宋体;"><span style="font-size:16px;"></span></span>
</p><div>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161227/14RR933C2520-19407.jpg{/dede:field}
