{dede:field name='keywords'}ARC700一体化智能装置成功上线{/dede:field}
{dede:field name='description'}ARC700一体化智能装置是悍客电气（上海）有限公司自主研发的一款集测控、保护、通信管理、网络交换为一体的智能化装置，产品适用于风电场箱变测控、光伏电场箱变测控、分布式并网接口装置、站所终端一体化子站；跨行业整合，极大的降低了用户成本，简化了设计{/dede:field}
{dede:field name='title'}ARC700一体化智能装置成功上线_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
