<?php
$z[0]=Array("noteinfo","",0,191);
$z[0][4]['notename']="11";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://www.humcore.com/case-item-369.html";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div class=\"pro\">\r\n	<ul class=\"clearfix\">\r\n					<li>{/dede:areastart}\r\n    {dede:areaend}				\r\n			</li>\r\n\r\n\r\n		    \r\n	</ul>\r\n</div>\r\n\r\n	\r\n		<ul class=\"fen\">{/dede:areaend}\r\n",193,712);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://www.humcore.com/case-1027-(*).html";
$z[1][4]['startid']="1";
$z[1][4]['endid']="2";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>