{dede:noteinfo notename="11" channelid="1" macthtype="string"
    refurl="http://www.humcore.com/case-item-369.html" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.humcore.com/case-1027-(*).html"
startid="1" endid="2" addv="1" urlrule="area" musthas=""
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="pro">
	<ul class="clearfix">
					<li>{/dede:areastart}
    {dede:areaend}				
			</li>


		    
	</ul>
</div>

	
		<ul class="fen">{/dede:areaend}
{/dede:listrule}
