<?php
$z[0]=Array("sppage","",0,73);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.humcore.com/case-item-369.html",75,151);
$z[2]=Array("keywordtrim","",153,190);
$z[3]=Array("descriptiontrim","",192,237);
$z[4]=Array("item","\r\n   {dede:match}<h1 class=\"news_t\">[ÄÚÈÝ]</h1>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",239,408);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",410,550);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",552,692);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}<p class=\"xbt\">[ÄÚÈÝ</p>{/dede:match}\r\n   \r\n   {dede:function}@me=GetMkTime(@me);{/dede:function}\r\n",694,878);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<div class=\"newsshow_div\">[ÄÚÈÝ]<p class=\"MsoNormal\" style=\"text-indent:2em;\">{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",880,1098);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>