<?php
$z[0]=Array("field","JZS-7G-42,JZS-7G-42电源监视继",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","悍客电气（上海）有限公司生产的HTM2-SWD.22控制电源监视继电器是JZS-7G-42电源监视继电器的技术革新产品，详情欢迎查阅www.humcore.com;",72,244);
$z[1][4]['name']="description";
$z[2]=Array("field","JZS-7G-42与HTM2-SWD.22控制电源监视继电器性能对比选型",246,336);
$z[2][4]['name']="title";
$z[3]=Array("field","",338,377);
$z[3][4]['name']="writer";
$z[4]=Array("field","",379,418);
$z[4][4]['name']="source";
$z[5]=Array("field","",420,460);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p class=\"MsoNormal\" align=\"center\" style=\"text-align:center;text-indent:2em;\">\r\n	<b><span style=\"font-size:16px;\">JZS-7G-42</span><span style=\"font-size:16px;\">与</span><span style=\"font-size:16px;\">HTM2-SWD.22</span><span style=\"font-size:16px;\">控制电源监视继电器性能对比选型</span></b><b></b>\r\n</p>",462,801);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161219/14R13513ALF-19443.jpg",803,887);
$z[7][4]['name']="litpic";

?>