{dede:field name='keywords'}电力配电自动化创新产品方案{/dede:field}
{dede:field name='description'}站所终端一体化智能装置符合中国电网发展趋势，也符合现在世界潮流的智能电网，大数据，互联网+的概念。创新产品结合技术选型引导，此产品必将成为未来配网自动化主流关键元件！{/dede:field}
{dede:field name='title'}电力配电自动化创新产品方案_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
