<?php
$z[0]=Array("sppage","",0,59);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.humcore.com/case-item-369.html",61,137);
$z[2]=Array("keywordtrim","",139,176);
$z[3]=Array("descriptiontrim","",178,223);
$z[4]=Array("item","\r\n   {dede:match}<h1 class=\"news_t\">[内容]</h1>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",225,394);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",394,534);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",534,674);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}发布时间：<p class=\"xbt\">[内容</p>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",674,849);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<div class=\"newsshow_div\">[内容]<div class=\"sx\">{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",849,1037);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>