<table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td height="35" align="center" class="font_05"><a href="[field:arcurl/]">[field:title/]</a></td>
                    </tr>
                    <tr>
                      <td class="font_04">
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="font_04_box">
  <tr>
    <td><div style="padding:3px;"><a href="[field:arcurl/]">[field:info/]...</a></div></td>
  </tr>
</table>			  </td>
                    </tr>
                  </table>