<?php
$z[0]=Array("arcurl","",81,96);
$z[1]=Array("picname","",108,124);
$z[2]=Array("arcurl","",226,241);
$z[3]=Array("title","",244,258);
$z[4]=Array("source","",322,337);
$z[5]=Array("writer","",356,371);
$z[6]=Array("pubdate","",391,438);
$z[6][4]['function']="MyDate('Y-m-d',@me)";
$z[7]=Array("description","",490,540);
$z[7][4]['function']="cn_substr(@me,300)";
$z[8]=Array("arcurl","",598,613);

?>