<?php
$z[0]=Array("include","",2,37);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",477,506);
$z[1][4]['name']="position";
$z[2]=Array("field","",693,751);
$z[2][4]['name']="typeid";
$z[2][4]['function']="GetTopTypename(@me)";
$z[3]=Array("channel","\r\n        <li>\r\n          <h2><a href=\"[field:typeurl/]\">[field:typename/]</a></h2>\r\n        </li>\r\n        ",826,1069);
$z[3][4]['type']="son";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='zyhove'>~typename~</a></li>";
$z[4]=Array("field","",1123,1144);
$z[4][4]['name']="content";
$z[5]=Array("include","",1288,1323);
$z[5][4]['filename']="foot.htm";

?>