<div class="pro_list wow fadeInUp" data-wow-delay=".2s">
              <div class="pro_item pro_list2">
                <div class="pro_item_img" style="background-image:url([field:picname/]);"></div>
                <div class="pro_item_title">
                  <h3><a href='[field:arcurl/]' target="_blank">[field:title/]</a></h3>
                  <h4>[field:description function="cn_substr(@me,60)"/]...</h4>
                </div>
              </div>
            </div>