{dede:field name='keywords'}HTR2-EWH.22小电流启动监视继电{/dede:field}
{dede:field name='description'}HTR2-EWH.22小电流启动监视继电器就悍客电气（上海）有限公司研制的新一代跳闸合闸回路监视继电器，采用欧规标准，外形性能比肩ABB、西门子、施耐德等国际品牌企业产品，具有极小的体积，极低功耗，极宽电压，节能环保，是最新小型化技术的代表！{/dede:field}
{dede:field name='title'}HTR2-EWH.22小电流启动监视继电器上线_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
