<?php
$z[0]=Array("field","HTM2-SWE.12间隔延时继电器上线",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","悍客电气（上海）有限公司的HTM2-SWE.12间隔延时继电器可替代ABB CT-VWD时间继电器,CT-VWS时间继电器，性能与外形比肩，性价比高，了解详情请查阅www.humcore.com",72,267);
$z[1][4]['name']="description";
$z[2]=Array("field","HTM2-SWE.12间隔延时继电器上线！_悍客电气（上海）有限公司",269,363);
$z[2][4]['name']="title";
$z[3]=Array("field","",365,404);
$z[3][4]['name']="writer";
$z[4]=Array("field","",406,445);
$z[4][4]['name']="source";
$z[5]=Array("field","",447,484);
$z[5][4]['name']="body";
$z[6]=Array("field","",486,526);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",528,567);
$z[7][4]['name']="litpic";

?>