{dede:field name='keywords'}HTM2-SWE.12间隔延时继电器上线{/dede:field}
{dede:field name='description'}悍客电气（上海）有限公司的HTM2-SWE.12间隔延时继电器可替代ABB CT-VWD时间继电器,CT-VWS时间继电器，性能与外形比肩，性价比高，了解详情请查阅www.humcore.com{/dede:field}
{dede:field name='title'}HTM2-SWE.12间隔延时继电器上线！_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
