<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",170,199);
$z[1][4]['name']="position";
$z[2]=Array("field","",385,404);
$z[2][4]['name']="title";
$z[3]=Array("field","",540,558);
$z[3][4]['name']="body";
$z[4]=Array("prenext","",638,663);
$z[4][4]['get']="pre";
$z[5]=Array("prenext","",668,694);
$z[5][4]['get']="next";
$z[6]=Array("include","",748,783);
$z[6][4]['filename']="foot.htm";

?>