{dede:field name='keywords'}JZ-7Y-38XMT,JZ-7Y-38XMS,JZ-7Y-{/dede:field}
{dede:field name='description'}HTR2-EWH.22跳位合位监视继电器是新一代替代JZ-7Y-38XMT,JZ-7Y-38XMS,跳位合位监视继电器的技术革新产品，具有体积极小，节能环保，外形美观的特点，符合欧州最先进的模数化小型化标准！{/dede:field}
{dede:field name='title'}JZ-7Y-38XMT（XMS）与HTR2-EWH.22跳位合位监视继电器性能对比选型{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p class="MsoNormal" align="center" style="text-align:center;text-indent:2em;">
	<b>JZ-7Y-38XMT<span>（</span><span>XMS</span><span>）与</span><span>HTR2-EWH.22</span><span>跳位合位监视继电器性能对比选型</span></b><b></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	一、<b>直观对比</b><b></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	1、<b>江阴新长江<span>JZ-7Y-38XMT</span><span>（</span><span>XMS</span><span>）跳位合位监视继电器外形</span></b><b></b> 
</p>
<p class="MsoNormal">
	<img src="/uploads/allimg/c161219/14R13560RR30-G628.png" alt="" /> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	2<span>、</span><b>江阴新长江<span>JZ-7Y-38XMT</span><span>（</span><span>XMS</span><span>）跳位合位监视继电器外形尺寸及安装方式</span></b><b></b> 
</p>
<p class="MsoNormal">
	<img src="/uploads/allimg/c161219/14R13560V2H0-U430.png" alt="" /> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	3、<b>江阴新长江<span>JZ-7Y-38XMT</span><span>（</span><span>XMS</span><span>）跳位合位监视继电器外观特点描述</span></b><b></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	A、<b>采用<span>JK-1</span><span>壳体</span></b><b></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<br />
</p>
<p class="MsoNormal" style="text-indent:21.0000pt;">
	K-1<span>壳体是阿城继电器厂上世纪</span><span>50</span><span>年代开发的一种凸出式插拔式电力继电器壳体，可板后接线安装（</span><span>JK-1</span><span>），也可加板前附件后板前接线安装（</span><span>JK-1Q</span><span>）。</span> 
</p>
<p class="MsoNormal" style="text-indent:21.0000pt;">
	JK-1<span>壳体是中国建国初期从前苏联引进的</span><span>10</span><span>壳体（凸出式固定接线结构）国产化改进而来，改进了</span><span>10</span><span>壳体接线端子少，维护拆装不便的缺点，为中国电力事业立下汗马功劳！</span> 
</p>
<p>
	<br />
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span></span><span></span><span></span><span></span><span></span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b>B<span>、安装需要专门开孔</span></b><b></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	JK-1<span>壳体不论是板后接线安装方式还是板前接线安装方式都需要开相应固定孔，组柜时必须考虑该继电器的开孔工序，增加人力、机器设备工作量，增加工艺控制难度！</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b>C<span>、外形尺寸巨大</span></b><b></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	如图<span>JK-11</span><span>壳体继电器最大外形达到</span><span>118X102X156mm</span><span>，与现代世界主流电力继电器产品来讲堪称巨大，在单元空间内的功能密度小，不利于现代成套产品小型化！</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b>D<span>、产品笨重（</span></b>不少于<span>2</span><span>斤），耗费材料多，组装工艺麻烦，除内部线路板外，组装工序还停留在基本靠人的状态。造成产品不论人工还是材料成本都高企不下，且工人不熟练极容易造成组装过程中的接触不良，造成产品运行隐患！</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b>E<span>、产品没有工业设计感，不美观！</span></b><b></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	4、<b>悍客电气<span>HTR2-EWH.22</span><span>小电流启动监视继电器外形</span></b><b></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<img src="/uploads/allimg/c161219/14R1356064N30-43248.png" alt="" /> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	5、<b>悍客电气<span>HTR2-EWH.22</span><span>小电流启动监视继电器外形尺寸及安装方式</span></b><b></b> 
</p>
<p class="MsoNormal">
	<img src="/uploads/allimg/c161219/14R13560CB10-54939.png" alt="" /> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	6、<b>悍客电气<span>HTR2-EWH.22</span><span>小电流启动监视继电器外观特点描述</span></b><b></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	A、<b>采用欧规<span>18mm</span><span>模数化结构壳体</span></b><b></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	欧规<span>18mm</span><span>模数化结构壳体是当前世界最先进的继电器壳体标准，国际巨头</span><span>ABB</span><span>、施耐德、西门子等知名企业均采用的壳体！</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	欧规<span>18mm</span><span>模数化结构壳体来源于欧美企业产品特征，由最初的</span><span>36mm</span><span>模数、</span><span>22.5mm</span><span>模数发展到现在的</span><span>18mm</span><span>模数。体现着当今电力电子技术不断的进步与产品的小型化技术潮流！</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b>B<span>、国际标准</span><span>35mm</span><span>导轨安装和万能固定式安装方式</span></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	悍客电气<span>HTR2-EWH.22</span><span>小电流启动监视继电器采用国际通用的</span><span>35mmDIN</span><span>导轨安装方式，在没有条件时其设计还可以实现两端螺丝固定的万能安装方式。</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b>C<span>、安装不用开孔</span></b><b></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	标准的<span>35mmDIN</span><span>导轨安装方式，只要一把小一字螺丝刀，</span><span>10</span><span>秒钟内就可完成产品的安装！相比老式</span><span>JK-11</span><span>壳体安装，节省人力，简化柜体加工工艺，避免额外的开孔加工！</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b>D<span>、极小的体积</span></b><b></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	悍客电气<span>HTR2-EWH.22</span><span>小电流启动监视继电器最大外形为</span><span>110X18X73.5mm</span><span>，体积几乎只有</span><span>JK-11</span><span>壳体的十分之一，极大的提高了成套产品的功能密度，极大的有利于成套产品的小型化，减少占地面积，节约土地资源，小型化电力产品！</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b>E<span>、重量轻</span></b>（不超过<span>2</span><span>两），节省材料，全表贴元件，标准化端子，板件标准化程度高，不依托人员专业水平，组装简单，大量的节省了人力成本，提高了产品的一致性和稳定性。</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b>F<span>、拥有自主专利的外观设计，人性化的壳体设计</span></b><b></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	1）外观比肩<span>ABB</span><span>、施耐德、西门子等国际巨头，拥有自主外观专利！</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	2）接线端子安全防护等级高，除非用专业工具，人手不可能碰到带电端子部分，彻底消除在安装、调试、检修时误碰裸露端子而造成人身伤亡事故的风险！
</p>
<p class="MsoNormal" style="text-indent:2em;">
	3）设计了专门的可拆装的标示牌，方便标识回路！提高回路现场阅读能力！
</p>
<p class="MsoNormal" style="text-indent:2em;">
	4）设计了专门的透明防尘罩，可铅封，既保证了观测的方便性，又保证了整定或标识在恶劣的环境下不被模糊！
</p>
<p class="MsoNormal" style="text-indent:2em;">
	7、<b>外形直观对比结论</b><b></b> 
</p>
<p style="text-indent:2em;">
	<table class="MsoTableGrid" style="width:426.1pt;">
		<tbody>
			<tr>
				<td width="106" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">对比项目</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="145" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:10.5000pt;">JZ-7Y-38XMT</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="175" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:10.5000pt;">HTR2-EWH.22</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="142" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">说明</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="106" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">壳体</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="145" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">JK-1</span> 
					</p>
				</td>
				<td width="175" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">欧规<span>18mm</span><span>模数结构</span></span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="142" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">前苏联产品引进产品改进技术与当下国际流行的小型模数化技术的差别</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="106" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">外形尺寸</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="145" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">118X102X156mm</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="175" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">110X18X73.5mm</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="142" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">悍客产品只有老产品的十分之一的体积</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="106" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:10.5000pt;">重量</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="145" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:10.5000pt;">不小于<span>2</span><span>斤</span></span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="175" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:10.5000pt;">不大于<span>2</span><span>两</span></span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="142" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">悍客产品只有老产品的十分之一的重量</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="106" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:10.5000pt;">外观</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="145" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:10.5000pt;">没有设计感，不美观，防护等级差，结构复杂，工艺难保证</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="175" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:10.5000pt;">一流的外观设计，比肩国际品牌，人性化设计，防护等级高，工艺标准化。</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="142" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">相差<span>60</span><span>年的技术进步差距</span></span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
			</tr>
		</tbody>
	</table>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	二、<b>关键参数对比</b><b></b> 
</p>
<p style="text-indent:2em;">
	<table class="MsoTableGrid" style="width:426.1pt;">
		<tbody>
			<tr>
				<td width="107" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">对比项目</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="141" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">JZ-7Y-38XMT</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="178" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">HTR2-EWH.22</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="142" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">说明</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="107" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">工作电流</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="141" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">4-6mA</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="178" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">不大于<span>3mA</span></span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="142" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">不需辅助电源</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="107" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">电压范围</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="141" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">50-300VDC</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="178" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">100-460V AC/DC</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="142" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">HTR2-EWH<span>实际可到</span><span>24-690V AC/DC</span></span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="107" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">抗干扰</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="141" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">&nbsp;</span> 
					</p>
				</td>
				<td width="178" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">国标最高标准：</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">静放电：四级（<span>8KV/15KV)</span></span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">群脉冲：四级（<span>4KV</span><span>）</span></span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">浪涌：四级（<span>4KV</span><span>）</span></span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="142" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;">HTR2-EWH<span>适应最严酷的工业环境！</span></span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
			</tr>
		</tbody>
	</table>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	三、<b>HTR2-EWH.22<span>小电流启动监视继电器原理先进性及元器件保证</span></b><b></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	1、采用仿<span>ABB</span><span>、西门子世界最先进的开关电源，极小体积，极高效率，不发热，极宽的工作电压，节能环保。</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	2、关键元件均采用<span>ABB</span><span>、西门子、施耐德等知名品牌产品同等档次元件，如出口继电器用美国泰科，电容用长寿命型松下电容，整定器件选择西班牙电位器，主控</span><span>CPU</span><span>先用美系工业级</span><span>ARM9</span><span>系列。所有选材不低于进口国际品牌产口。</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	四、<b>产品性价比</b><b></b> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	由于产品技术的进步，用材的节省，悍客电气（上海）有限公司<span>HTR2-EWH.22</span><span>小电流启动监视继电器在性价比上相对老式壳体产品有明显优势！</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	愿与您一起推动技术革新，共创美好未来！
</p>
<p class="MsoNormal" style="text-indent:2em;">
	详情请致电我们<span>---------</span><span>悍客电气（上海）有限公司</span> 
</p>
<p class="MsoNormal">
	<span><img src="/uploads/allimg/c161219/14R13560Da60-B220.png" alt="" /><br />
</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:18px;color:#000000;"><strong>更多相关文章</strong></span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:18px;"><strong><a href="http://www.humcore.com/article-item-301.html" target="_blank"><strong><span style="color:#99BB00;">分合闸继电器的特点、应用和选型</span></strong></a></strong></span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:18px;"><strong><a href="http://www.humcore.com/product-item-461.html" target="_blank"><strong><span style="color:#99BB00;">HTR2-EWH系列小电流启动监视继电器</span></strong></a></strong></span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:18px;"><a href="http://www.humcore.com/case-item-265.html" target="_blank"><strong><span style="color:#99BB00;">电力继电器的分类及选型</span></strong></a></span> 
</p>

		</div>
</div>





	
	
	<script>
		$.ajax({
			url : "/case-getClick-317.html",
			success : function(data){
				$('#click').html(data);
			}
		});
	</script>
		
</div></div><div class="place column" name="case_pre_info"><div class="module no_edit" style="">{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161219/14R135131262P-11P4.jpg{/dede:field}
