{dede:field name='keywords'}悍客电气HTM2-MWR.22循环时间不{/dede:field}
{dede:field name='description'}悍客电气（上海）有限公司研制的HTM2-MWR.22循环时间不等时间继电器是一款18mm欧规模数化电子时间继电器，采用世界先进的电源方案，产品具有小型、环保、长寿命、高抗扰度的特点，外观性能比肩ABB、西门子、施耐德等国际品牌产品，是理想的替代产品！{/dede:field}
{dede:field name='title'}悍客电气HTM2-MWR.22循环时间不等时间继电器成功上线_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
