{dede:field name='keywords'}JZS-7G-42,JZS-7G-42电源监视继{/dede:field}
{dede:field name='description'}悍客电气（上海）有限公司生产的HTM2-SWD.22控制电源监视继电器是JZS-7G-42电源监视继电器的技术革新产品，详情欢迎查阅www.humcore.com;{/dede:field}
{dede:field name='title'}JZS-7G-42与HTM2-SWD.22控制电源监视继电器性能对比选型{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p class="MsoNormal" align="center" style="text-align:center;text-indent:2em;">
	<b><span style="font-size:16px;">JZS-7G-42</span><span style="font-size:16px;">与</span><span style="font-size:16px;">HTM2-SWD.22</span><span style="font-size:16px;">控制电源监视继电器性能对比选型</span></b><b></b>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">一、</span><b><span style="font-size:16px;">直观对比</span></b><b></b>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">1、</span><b><span style="font-size:16px;">江阴新长江</span><span style="font-size:16px;">JZS-7G-42控制电源</span><span style="font-size:16px;">监视继电器外形</span></b><b></b>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;"></span><img src="/uploads/allimg/c161219/14R1356201K60-1V38.png" alt="" />
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">2</span><span style="font-size:16px;">、</span><b><span style="font-size:16px;">江阴新长江</span><span style="font-size:16px;">JZS-7G-42控制电源</span><span style="font-size:16px;">监视继电器外形尺寸及安装方式</span></b><b></b>
</p>
<p class="MsoNormal">
	<img src="/uploads/allimg/c161219/14R1356215030-23044.png" alt="" /><span style="font-size:16px;"></span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">3、</span><b><span style="font-size:16px;">江阴新长江</span><span style="font-size:16px;">JZS-7G-42控制电源</span><span style="font-size:16px;">监视继电器外观特点描述</span></b><b></b>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">A、</span><b><span style="font-size:16px;">采用60</span><span style="font-size:16px;">mm</span><span style="font-size:16px;">导轨壳体</span></b><b></b>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">如图所示江阴新长江</span><b><span style="font-size:16px;">JZS-7G-42</span></b><span style="font-size:16px;">采用的壳体为仿菲尼克斯导轨壳体，适用于标准</span><span style="font-size:16px;">35mmDIN</span><span style="font-size:16px;">导轨安装，属于欧美较老式一代的导轨壳体，大概在</span><span style="font-size:16px;">2010</span><span style="font-size:16px;">年前后在国内引用改进！是电力继电器小型化导轨化的第一代壳体，现在大量使用！</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b><span style="font-size:16px;">B</span><span style="font-size:16px;">、国际标准</span><span style="font-size:16px;">35mm</span><span style="font-size:16px;">导轨安装</span></b><b></b>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b><span style="font-size:16px;">C</span><span style="font-size:16px;">、安装不用开孔</span></b><b></b>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">标准的</span><span style="font-size:16px;">35mmDIN</span><span style="font-size:16px;">导轨安装方式，只要一把小一字螺丝刀，</span><span style="font-size:16px;">10</span><span style="font-size:16px;">秒钟内就可完成产品的安装！相比老式</span><span style="font-size:16px;">JK-11</span><span style="font-size:16px;">壳体安装，节省人力，简化柜体加工工艺，避免额外的开孔加工！</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b><span style="font-size:16px;">D</span><span style="font-size:16px;">、较小的体积</span></b><b></b>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">江阴新长江</span><span style="font-size:16px;">JZS-7G-42控制电源</span><span style="font-size:16px;">监视继电器外形最大为</span><span style="font-size:16px;">90X60X68mm</span><span style="font-size:16px;">体积为老式</span><span style="font-size:16px;">JK-1</span><span style="font-size:16px;">或</span><span style="font-size:16px;">JK-11</span><span style="font-size:16px;">壳体的三分之一左右，提高了成套产品的功能密度，</span><span style="font-size:16px;">极大的有利于成套产品的小型化，减少占地面积，节约土地资源，小型化电力产品！</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b><span style="font-size:16px;">E</span><span style="font-size:16px;">、重量轻</span></b><span style="font-size:16px;">（不超过</span><span style="font-size:16px;">2</span><span style="font-size:16px;">两），节省材料，标准化端子，板件标准化程度高，不依托人员专业水平，组装简单，大量的节省了人力成本，提高了产品的一致性和稳定性。</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b><span style="font-size:16px;">F</span><span style="font-size:16px;">、人性化的壳体设计</span></b><b></b>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">1）外形美观</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">2）巧妙的透明罩设计，既提高了端子的防护等级，又方便观察内部元件状态（这个造成产品一定的不美观）</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">4、</span><b><span style="font-size:16px;">悍客电气</span><span style="font-size:16px;">HTM2-SWD.22控制电源</span><span style="font-size:16px;">监视继电器外形</span></b><b></b>
</p>
<p class="MsoNormal">
	<img src="/uploads/allimg/c161219/14R13513ALF-19443.jpg" alt="" /><span style="font-size:16px;"></span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">5、</span><b><span style="font-size:16px;">悍客电气</span><span style="font-size:16px;">HTM2-SWD.22</span><span style="font-size:16px;">控制电源监视继电器外形尺寸及安装方式</span></b><b></b>
</p>
<p class="MsoNormal">
	<img src="/uploads/allimg/c161219/14R13560CB10-54939.png" alt="" /> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">6、</span><b><span style="font-size:16px;">悍客电气</span><span style="font-size:16px;">HTM2-SWD.22控制电源</span><span style="font-size:16px;">监视继电器外观特点描述</span></b><b></b>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">A、</span><b><span style="font-size:16px;">采用欧规</span><span style="font-size:16px;">18mm</span><span style="font-size:16px;">模数化结构壳体</span></b><b></b>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">欧规</span><span style="font-size:16px;">18mm</span><span style="font-size:16px;">模数化结构壳体是当前世界最先进的继电器壳体标准，国际巨头</span><span style="font-size:16px;">ABB</span><span style="font-size:16px;">、施耐德、西门子等知名企业均采用的壳体！</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">欧规</span><span style="font-size:16px;">18mm</span><span style="font-size:16px;">模数化结构壳体来源于欧美企业产品特征，由最初的</span><span style="font-size:16px;">36mm</span><span style="font-size:16px;">模数、</span><span style="font-size:16px;">22.5mm</span><span style="font-size:16px;">模数发展到现在的</span><span style="font-size:16px;">18mm</span><span style="font-size:16px;">模数。体现着当今电力电子技术不断的进步与产品的小型化技术潮流！</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b><span style="font-size:16px;">B</span><span style="font-size:16px;">、国际标准</span><span style="font-size:16px;">35mm</span><span style="font-size:16px;">导轨安装和万能固定式安装方式</span></b>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">悍客电气</span><span style="font-size:16px;">HTM2-SWD.22</span><span style="font-size:16px;">小电流启动监视继电器采用国际通用的</span><span style="font-size:16px;">35mmDIN</span><span style="font-size:16px;">导轨安装方式，在没有条件时其设计还可以实现两端螺丝固定的万能安装方式。</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b><span style="font-size:16px;">C</span><span style="font-size:16px;">、安装不用开孔</span></b><b></b>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">标准的</span><span style="font-size:16px;">35mmDIN</span><span style="font-size:16px;">导轨安装方式，只要一把小一字螺丝刀，</span><span style="font-size:16px;">10</span><span style="font-size:16px;">秒钟内就可完成产品的安装！相比老式</span><span style="font-size:16px;">JK-11</span><span style="font-size:16px;">壳体安装，节省人力，简化柜体加工工艺，避免额外的开孔加工！</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b><span style="font-size:16px;">D</span><span style="font-size:16px;">、极小的体积</span></b><b></b>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">悍客电气</span><span style="font-size:16px;">HTM2-SWD.22控制电源</span><span style="font-size:16px;">监视继电器最大外形为</span><span style="font-size:16px;">110X18X73.5mm</span><span style="font-size:16px;">，体积几乎只有</span><span style="font-size:16px;">JK-11</span><span style="font-size:16px;">壳体的十分之一，极大的提高了成套产品的功能密度，极大的有利于成套产品的小型化，减少占地面积，节约土地资源，小型化电力产品！</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b><span style="font-size:16px;">E</span><span style="font-size:16px;">、重量轻</span></b><span style="font-size:16px;">（不超过</span><span style="font-size:16px;">2</span><span style="font-size:16px;">两），节省材料，全表贴元件，标准化端子，板件标准化程度高，不依托人员专业水平，组装简单，大量的节省了人力成本，提高了产品的一致性和稳定性。</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b><span style="font-size:16px;">F</span><span style="font-size:16px;">、拥有自主专利的外观设计，人性化的壳体设计</span></b><b></b>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">1）</span><span style="font-size:16px;">外观比肩</span><span style="font-size:16px;">ABB</span><span style="font-size:16px;">、施耐德、西门子等国际巨头，拥有自主外观专利！</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">2）接线端子安全防护等级高，除非用专业工具，人手不可能碰到带电端子部分，彻底消除在安装、调试、检修时误碰裸露端子而造成人身伤亡事故的风险！</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">3）设计了专门的可拆装的标示牌，方便标识回路！提高回路现场阅读能力！</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">4）设计了专门的透明防尘罩，可铅封，既保证了观测的方便性，又保证了整定或标识在恶劣的环境下不被模糊！</span>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<span style="font-size:16px;">7、</span><b><span style="font-size:16px;">外形直观对比结论</span></b><b></b>
</p>
<p style="text-indent:2em;">
	<table class="MsoTableGrid" style="width:426.1pt;">
		<tbody>
			<tr>
				<td width="106" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:16px;">对比项目</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="145" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:16px;">JZS-7G-42</span><span style="font-family:宋体;font-size:10.5000pt;"></span>
					</p>
				</td>
				<td width="175" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:16px;">HTM2-SWD.22</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="142" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:16px;">说明</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="106" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:16px;">壳体</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="145" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;"><span style="font-size:16px;">导轨60</span><span style="font-size:16px;">mm</span><span style="font-size:16px;">模数结构</span></span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="175" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:10.5000pt;"><span style="font-size:16px;">欧规</span><span style="font-size:16px;">18mm</span><span style="font-size:16px;">模数结构</span></span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="142" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:16px;">欧规老一代与最新一代的差别</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="106" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:16px;">外形尺寸</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="145" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:16px;">90X60X68mm</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="175" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:16px;">110X18X73.5mm</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="142" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:16px;">悍客产品有着更小的体积，比江阴产品小一半</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="106" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:16px;">重量</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="145" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:10.5000pt;"><span style="font-size:16px;">不大于</span><span style="font-size:16px;">2</span><span style="font-size:16px;">两</span></span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="175" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:10.5000pt;"><span style="font-size:16px;">不大于</span><span style="font-size:16px;">2</span><span style="font-size:16px;">两</span></span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="142" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:16px;">由于均采用欧规壳体，电子线路，此项基本相当</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
			</tr>
			<tr>
				<td width="106" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:16px;">外观</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="145" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:16px;">外形美观，有巧妙的透明罩设计，但因此内部元件暴露在外，影响美观！</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="175" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal" style="margin-left:0.0000pt;text-indent:0.0000pt;">
						<span style="font-family:宋体;font-size:16px;">一流的外观设计，比肩国际品牌，人性化设计，防护等级高，有专门的标示牌设计。</span><span style="font-family:宋体;font-size:10.5000pt;"></span> 
					</p>
				</td>
				<td width="142" valign="top" style="border:1.0000pt solid windowtext;">
					<p class="MsoNormal">
						<span style="font-family:宋体;font-size:16px;">悍客产品有着更美观和人性化的优势！</span>
					</p>
				</td>
			</tr>
		</tbody>
	</table>
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<b>
	<p class="MsoNormal">
		<!--[if !supportLists]--><span style="font-size:16px;">二、</span><!--[endif]--><b><span style="font-size:16px;">工作原理对比</span></b><b><o:p></o:p></b>
	</p>
	<p class="MsoNormal">
		<span style="font-size:16px;">JZS-7/244</span><span style="font-family:宋体;font-size:16px;">断电延时继电器采用高压储能实现断电后继电器延时期间的能量供给，此电路上电有较大冲击电流（电容在上电瞬间相当于短路），对控制电源本身有较大冲击，容易造成保险熔断或空开跳闸。另外，由于采用高压铝电解电容，在高温和长期通电的情况下电容会自然衰减，使用一段时间后其储能性能下降，达不到设计要求的延时。输出继电器采用单位置继电器通过大功率电阻降压保持动作状态，功耗较大，电阻发热严重，电阻容易老化失效！高压电解电容，大功率电阻体积都比较大，产品难以小型化。</span><o:p></o:p>
	</p>
	<p class="MsoNormal">
		<span style="font-size:16px;">HTM2-SWD.22</span><span style="font-family:宋体;font-size:16px;">断电延时继电器采用国际最先进的开关电源效率达到</span><span style="font-family:Calibri;font-size:16px;">95%</span><span style="font-family:宋体;font-size:16px;">以上无发热元件，出口采用双位置磁保持继电器，储能采用低压超级电容，断电后主控制器进入睡眠模式，只进行延时计数功能（功耗极低，</span><span style="font-family:Calibri;font-size:16px;">uA</span><span style="font-family:宋体;font-size:16px;">级），延时到中断唤醒，用储存的能量动作返回。</span><o:p></o:p>
	</p>
	<p class="MsoNormal">
		<span style="font-size:16px;">JZS-7/244</span><span style="font-family:宋体;font-size:16px;">断电延时电路只能按特定规格匹配电容，电压等级越低，为了保证断电后的延时，电容容量越大，电流冲击越大，超过</span><span style="font-family:Calibri;font-size:16px;">220V</span><span style="font-family:宋体;font-size:16px;">以上，由于高压电解电容耐压限制，无法实现</span><span style="font-family:Calibri;font-size:16px;">380V</span><span style="font-family:宋体;font-size:16px;">及以上的控制电源规格。</span><o:p></o:p>
	</p>
	<p class="MsoNormal">
		<span style="font-size:16px;">HTM2-SWD.22</span><span style="font-family:宋体;font-size:16px;">断电延时继电器由于采用国际上与西门子同步的开关电源，其本身可达到</span><span style="font-family:Calibri;font-size:16px;">24-690V</span><span style="font-family:宋体;font-size:16px;">交直流通用，国内外</span><span style="font-family:Calibri;font-size:16px;">50/60HZ</span><span style="font-family:宋体;font-size:16px;">通用，适用全球任何一种电压等级，且储能容量与输入的控制电压等级无关，明显有原理上的先进性。</span><o:p></o:p>
	</p>
	<p class="MsoNormal">
		<span style="font-size:16px;">HTM2-SWD.22</span><span style="font-family:宋体;font-size:16px;">获益于国际先进的电源电路，不发热，元件可表贴，因此在极大的输入电压范围内还可实现产品小型化，整个电路只在</span><span style="font-family:Calibri;font-size:16px;">18mm</span><span style="font-family:宋体;font-size:16px;">宽度的壳体中实现，是现行全球范围内最先进的断电延时继电器之一。</span>
	</p>
	<p class="MsoNormal">
		<!--[if !supportLists]--><span style="font-size:16px;">三、</span><!--[endif]--><b><span style="font-size:16px;">HTM2-SWD.22</span><span style="font-family:宋体;font-size:16px;">控制电源监视继电器原理先进性及元器件保证</span></b><b><o:p></o:p></b>
	</p>
	<p class="MsoNormal">
		<!--[if !supportLists]--><span style="font-size:16px;">1、</span><!--[endif]--><span style="font-family:宋体;font-size:16px;">采用仿</span><span style="font-size:16px;">ABB</span><span style="font-family:宋体;font-size:16px;">、西门子世界最先进的开关电源，极小体积，极高效率，不发热，极宽的工作电压，节能环保。</span><o:p></o:p>
	</p>
	<p class="MsoNormal">
		<!--[if !supportLists]--><span style="font-size:16px;">2、</span><!--[endif]--><span style="font-family:宋体;font-size:16px;">关键元件均采用</span><span style="font-size:16px;">ABB</span><span style="font-family:宋体;font-size:16px;">、西门子、施耐德等知名品牌产品同等档次元件，如出口继电器用美国泰科，电容用长寿命型松下电容，整定器件选择西班牙电位器，主控</span><span style="font-family:Calibri;font-size:16px;">CPU</span><span style="font-family:宋体;font-size:16px;">先用美系工业级</span><span style="font-family:Calibri;font-size:16px;">ARM9</span><span style="font-family:宋体;font-size:16px;">系列。所有选材不低于进口国际品牌产口。</span><o:p></o:p>
	</p>
	<p class="MsoNormal">
		<!--[if !supportLists]--><span style="font-size:16px;">四、</span><!--[endif]--><b><span style="font-size:16px;">产品性价比</span></b><b><o:p></o:p></b>
	</p>
	<p class="MsoNormal">
		<span style="font-family:宋体;font-size:16px;">由于产品技术的进步，用材的节省，悍客电气（上海）有限公司</span><span style="font-size:16px;">HTM2-SWD.22</span><span style="font-family:宋体;font-size:16px;">控制电源监视继电器在性价比上相对老式壳体产品有明显优势！</span><o:p></o:p>
	</p>
	<p class="MsoNormal">
		<span style="font-size:16px;">愿与您一起推动技术革新，共创美好未来！</span><o:p></o:p>
	</p>
	<p class="MsoNormal">
		<span style="font-family:宋体;font-size:16px;">详情请致电我们</span><span style="font-size:16px;">---------</span><span style="font-family:宋体;font-size:16px;">悍客电气（上海）有限公司</span>
	</p>
</b>
</p>
<p class="MsoNormal">
	<span><img src="/uploads/allimg/c161219/14R13560Da60-B220.png" alt="" /><br />
</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<br />
</p>

		</div>
</div>





	
	
	<script>
		$.ajax({
			url : "/case-getClick-369.html",
			success : function(data){
				$('#click').html(data);
			}
		});
	</script>
		
</div></div><div class="place column" name="case_pre_info"><div class="module no_edit" style="">{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161219/14R13513ALF-19443.jpg{/dede:field}
