<?php
$z[0]=Array("item","",4,86);
$z[0][4]['name']="参考文档";
$z[0][4]['link']="http://help.炫乐科技.com";
$z[0][4]['rank']="";
$z[0][4]['target']="_blank";
$z[1]=Array("item","",90,182);
$z[1][4]['name']="意见建议反馈";
$z[1][4]['link']="http://site.desdev.cn/suggest/";
$z[1][4]['rank']="";
$z[1][4]['target']="_blank";
$z[2]=Array("item","",186,271);
$z[2][4]['name']="官方交流论坛";
$z[2][4]['link']="http://bbs.炫乐科技.com";
$z[2][4]['rank']="";
$z[2][4]['target']="_blank";

?>