{dede:noteinfo notename="¼¼ÊõÎÄµµ" channelid="1" macthtype="string"
    refurl="http://" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.humcore.com/case-item-(*).html"
startid="1" endid="2" addv="1" urlrule="area" musthas=".html"
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="newsshow_div">{/dede:areastart}
    {dede:areaend}<ul class="fen">{/dede:areaend}
{/dede:listrule}
