<?php
$z[0]=Array("field","",76,104);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",113,142);
$z[1][4]['name']="typename";
$z[2]=Array("field","",144,173);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n              <li><a href='[field:typeurl/]' title=\"[field:typename/]\">[field:typename/]</a></li>\r\n              ",217,385);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>