{dede:field name='keywords'}悍客电气HTM2-MWR.21占空比不等{/dede:field}
{dede:field name='description'}悍客电气HTM2-MWR.21时间继电器是占空比不等延时继电器，外观性能比肩ABB、施耐德、西门子等国际公司，是理想的替代产品！{/dede:field}
{dede:field name='title'}悍客电气HTM2-MWR.21占空比不等时间继电器成功上线！{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p class="MsoNormal">
	悍客电气<o:p></o:p>
</p>
<p class="MsoNormal">
	<!--[if !supportLists]-->一、<!--[endif]-->基本信息<o:p></o:p>
</p>
<p class="MsoNormal">
	产品名称：欧规模数化电子时间继电器<o:p></o:p>
</p>
<p class="MsoNormal">
	产品型号：<span style="font-family:Calibri;">HTM2-MWR.21</span><o:p></o:p>
</p>
<p class="MsoNormal">
	控制电压：① <span style="font-family:Calibri;">24-240V AC 24-48V DC 50/60HZ</span><span style="font-family:宋体;">或</span><span style="font-family:Calibri;">DC</span><o:p></o:p>
</p>
<p class="MsoNormal">
	② <span style="font-family:Calibri;">12-240V AC/DC 50/60HZ</span><span style="font-family:宋体;">或</span><span style="font-family:Calibri;">DC</span><o:p></o:p>
</p>
<p class="MsoNormal">
	③ <span style="font-family:Calibri;">100-460V AC/DC 50/60HZ</span><span style="font-family:宋体;">或</span><span style="font-family:Calibri;">DC</span><o:p></o:p>
</p>
<p class="MsoNormal">
	④ <span style="font-family:Calibri;">160-690V AC/DC 50/60HZ</span><span style="font-family:宋体;">或</span><span style="font-family:Calibri;">DC</span><o:p></o:p>
</p>
<p class="MsoNormal">
	四选一<o:p></o:p>
</p>
<p class="MsoNormal">
	转换触点：一付延时转换接点一付瞬动转换接点（<span style="font-family:Calibri;">8A</span><span style="font-family:宋体;">）</span><o:p></o:p>
</p>
<p class="MsoNormal">
	工作模式：非等周期循环延时（脉冲发生器<span style="font-family:Calibri;">ON</span><span style="font-family:宋体;">或</span><span style="font-family:Calibri;">OFF</span><span style="font-family:宋体;">开始（循环时间不相等），占空比不等延时），多档位时间设定 </span><o:p></o:p>
</p>
<p class="MsoNormal">
	延时规格：<span style="font-family:Calibri;">0.05-1s 0.5-10s 5-100s 0.5-10min 5-100min 0.5-10h 5-100h</span><span style="font-family:宋体;">七档可调</span><span style="font-family:Calibri;">;</span><o:p></o:p>
</p>
<p class="MsoNormal">
	模数规格：<span style="font-family:Calibri;">18mm</span><o:p></o:p>
</p>
<p class="MsoNormal">
	<!--[if !supportLists]-->二、<!--[endif]-->可覆盖的国外相关产品型号<o:p></o:p>
</p>
<p class="MsoNormal">
	ABB: <span style="font-family:宋体;">无直接对应</span><o:p></o:p>
</p>
<p class="MsoNormal">
	可覆盖一组接点非等周期循环多档延时的<span style="font-family:Calibri;">CT-TGD </span><span style="font-family:宋体;">（</span><span style="font-family:Calibri;">1SVR 500 160 R 0000</span><span style="font-family:宋体;">） </span><span style="font-family:Calibri;">CT-TGS </span><span style="font-family:宋体;">（</span><span style="font-family:Calibri;">1SVR 430 163 R 0100</span><span style="font-family:宋体;">）</span><o:p></o:p>
</p>
<p class="MsoNormal">
	可覆盖一组接点等周期循环多档延时的<span style="font-family:Calibri;">CT-EBD </span><span style="font-family:宋体;">（</span><span style="font-family:Calibri;">1SVR 500 150 R 0000</span><span style="font-family:宋体;">） </span><span style="font-family:Calibri;">CT-EBS </span><span style="font-family:宋体;">（</span><span style="font-family:Calibri;">1SVR 430 152 R 0100</span><span style="font-family:宋体;">）</span><o:p></o:p>
</p>
<p class="MsoNormal">
	可覆盖一组接点等周期单档延时的<span style="font-family:Calibri;">CT-EBE </span><span style="font-family:宋体;">（</span><span style="font-family:Calibri;">1SVR 550 167 R 1100</span><span style="font-family:宋体;">（</span><span style="font-family:Calibri;">10S</span><span style="font-family:宋体;">） </span><span style="font-family:Calibri;">1SVR 550 160 R 1100</span><span style="font-family:宋体;">（</span><span style="font-family:Calibri;">10S</span><span style="font-family:宋体;">））</span><o:p></o:p>
</p>
<p class="MsoNormal">
	施耐德： 无直接对应<o:p></o:p>
</p>
<p class="MsoNormal">
	可覆盖一组接点非等周期循环多档延时的RE11RLJU RE11RLMU RE7CV11BU <o:p></o:p>
</p>
<p class="MsoNormal">
	可覆盖一组接点等周期循环多档延时的RE7CL11BU<o:p></o:p>
</p>
<p class="MsoNormal">
	西门子： 无直接对应<o:p></o:p>
</p>
<p class="MsoNormal">
	可覆盖一组接点非等周期循环多档延时的<span style="font-family:Calibri;">3RP1555-1AR30 3RP1555-1AQ30 3RP1555-1AP30</span><o:p></o:p>
</p><div>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c161227/14RRVa61K0-12606.png{/dede:field}
