<table border="0" cellspacing="5" cellpadding="0" width="98%">
                              <tbody>
                                    <tr>
                                      <td align="middle">[field:imglink/]</td>
                                    </tr>
                                    <tr>
                                      <td align="middle">[field:textlink/]</td>
                                    </tr>
                                </tbody>
                              </table>