{dede:field name='keywords'}CT-YDEW,CT-YDAV,RE7YA12BU,RE7Y{/dede:field}
{dede:field name='description'}悍客电气（上海）有限公司生产的HTM2-MWS.22时间继电器可替代进口CT-YDEW,CT-YDAV,RE7YA12BU,RE7YR12BU型多当位转换时间可调星三角转换时间继电器。详情请查阅www.humcore.com;{/dede:field}
{dede:field name='title'}替代进口多档位转换时间可调星三角转换时间继电器_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
