<?php
$z[0]=Array("addurls","",6,35);
$z[1]=Array("batchrule","",41,74);
$z[2]=Array("regxrule","",80,111);
$z[3]=Array("areastart","<!-- 案例 -->",117,163);
$z[4]=Array("areaend","<ul class=\"fen\">\r\n				<span class=\"page-disabled\">&laquo; 首页</span><span class=\"page-disabled control\">&#8249; 前一页</span><span class=\"page-num page-cur background fontcolor\">1</span><a class=\"page-num\" href=\"/case-1027-2.html\">2</a><a class=\"control\" href=\"/case-1027-2.html\">下一页 &#8250;</a><a href=\"/case-1027-2.html\">末页 &raquo;</a>\r\n		</ul>",169,550);

?>