
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<!-- 案例 -->{/dede:areastart}
    {dede:areaend}<ul class="fen">
				<span class="page-disabled">&laquo; 首页</span><span class="page-disabled control">&#8249; 前一页</span><span class="page-num page-cur background fontcolor">1</span><a class="page-num" href="/case-1027-2.html">2</a><a class="control" href="/case-1027-2.html">下一页 &#8250;</a><a href="/case-1027-2.html">末页 &raquo;</a>
		</ul>{/dede:areaend}
