<?php
$z[0]=Array("field","HTR2-EWH.22,HTR2-EWH.22继电器,",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","HTR2-EWH.22交直流信号转换继电器是悍客电气（上海）有限公司研制的一款低功耗，宽范围输入的转换继电器，HTR2-EWH.22继电器功耗不超1W，HTR2-EWH.22转换继电器电压适应24-690V AC/DC 特别适用于高电压和特殊电压应用场合。",73,324);
$z[1][4]['name']="description";
$z[2]=Array("field","HTR2-EWH.22交直流信号转换继电器_悍客电气（上海）有限公司",326,420);
$z[2][4]['name']="title";
$z[3]=Array("field","",422,461);
$z[3][4]['name']="writer";
$z[4]=Array("field","",463,502);
$z[4][4]['name']="source";
$z[5]=Array("field","",504,541);
$z[5][4]['name']="body";
$z[6]=Array("field","",543,583);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",585,624);
$z[7][4]['name']="litpic";

?>