{dede:field name='keywords'}HTR2-EWH.22,HTR2-EWH.22继电器,{/dede:field}
{dede:field name='description'}HTR2-EWH.22交直流信号转换继电器是悍客电气（上海）有限公司研制的一款低功耗，宽范围输入的转换继电器，HTR2-EWH.22继电器功耗不超1W，HTR2-EWH.22转换继电器电压适应24-690V AC/DC 特别适用于高电压和特殊电压应用场合。{/dede:field}
{dede:field name='title'}HTR2-EWH.22交直流信号转换继电器_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
