<?php
$z[0]=Array("field","HJTHW,HJTHW跳合位监视继电器",0,68);
$z[0][4]['name']="keywords";
$z[1]=Array("field","悍客电气（上海）有限公司生产的HTR2-EWH.22小电流启动监视继电器是HJTHW跳合位监视继电器的技术革新产品，详情欢迎查阅www.humcore.com;",70,242);
$z[1][4]['name']="description";
$z[2]=Array("field","HJTHW与HTR2-EWH.22跳位合位监视继电器性能对比选型",244,330);
$z[2][4]['name']="title";
$z[3]=Array("field","",332,371);
$z[3][4]['name']="writer";
$z[4]=Array("field","",373,412);
$z[4][4]['name']="source";
$z[5]=Array("field","",414,454);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p class=\"MsoNormal\" align=\"center\" style=\"text-align:center;text-indent:2em;\">\r\n	<b><span>HJTHW与</span><span>HTR2-EWH.22</span><span>跳位合位监视继电器性能对比选型</span></b><b></b>\r\n</p>",456,682);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c161219/14R135131262P-11P4.jpg",684,769);
$z[7][4]['name']="litpic";

?>