{dede:noteinfo notename="11" channelid="1" macthtype="string"
refurl="http://www.humcore.com/case-item-369.html" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.humcore.com/case-1027-(*).html"
startid="1" endid="2" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="newsshow_div">{/dede:areastart}
    {dede:areaend}<p class="MsoNormal">
	详情请致电我们<span>---------</span><span>悍客电气（上海）有限公司</span> 
</p>
{/dede:areaend}
{/dede:listrule}
