{dede:field name='keywords'}悍客电气HTM2-SWC.22多档通电延{/dede:field}
{dede:field name='description'}HTM2-SWC.22时间继电器是悍客电气（上海）有限公司自主研发的多档位通电延时欧规18mm宽度模数化继电器，外形与性能比肩ABB、西门子、施耐德等国际知名品牌公司，是进口高档继电器的理想替代产品！{/dede:field}
{dede:field name='title'}悍客电气HTM2-SWC.22多档通电延时时间继电器上线_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
