<?php
$z[0]=Array("pubdate","",76,119);
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",162,207);
$z[1][4]['function']="MyDate('Y-m',@me)";
$z[2]=Array("arcurl","",301,316);
$z[3]=Array("title","",325,339);
$z[4]=Array("title","",342,356);
$z[5]=Array("description","",401,451);
$z[5][4]['function']="cn_substr(@me,160)";
$z[6]=Array("arcurl","",482,497);
$z[7]=Array("title","",506,520);

?>