{dede:field name='keywords'}控制电源监视继电器的特点、应用{/dede:field}
{dede:field name='description'}为什么要监视控制电源各成套柜或控制柜中的控制电源一般取自电源小母线，在每个柜中装熔丝或空开，保证某一柜内发生短路故障时不影响总电源母线的正常供电。那么，若某个柜子的保险或空开跳开，那么这个柜子的控制电源就消失了，这个控制电源是最后驱动断路器{/dede:field}
{dede:field name='title'}控制电源监视继电器的特点、应用及选型_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
