{dede:noteinfo notename="11" channelid="1" macthtype="string"
    refurl="http://www.humcore.com/case-item-369.html" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.humcore.com/case-1027-(*).html"
startid="1" endid="2" addv="1" urlrule="area" musthas=""
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="pro">
	<ul class="clearfix">
					<li>{/dede:areastart}
    {dede:areaend}				
			</li>


		    
	</ul>
</div>

	
		<ul class="fen">{/dede:areaend}
{/dede:listrule}
{dede:sppage sptype='full' srul='1' erul='5'}{/dede:sppage}
{dede:previewurl}http://www.humcore.com/case-item-309.html{/dede:previewurl}
{dede:keywordtrim}{/dede:keywordtrim}
{dede:descriptiontrim}{/dede:descriptiontrim}
{dede:item field='title' value='' isunit='' isdown=''}
   {dede:match}<h1 class="news_t">[ÄÚÈÝ]</h1>{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}{dede:item field='writer' value='' isunit='' isdown=''}
   {dede:match}{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}{dede:item field='source' value='' isunit='' isdown=''}
   {dede:match}{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}{dede:item field='pubdate' value='' isunit='' isdown=''}
   {dede:match}{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}{dede:item field='body' value='' isunit='1' isdown='1'}
   {dede:match}<div class="newsshow_div">[ÄÚÈÝ]<p class="MsoNormal">
	<span><img src="data/site_user3741/public/201608/20160818/2016081808021899901.png" alt="" /><br />
</span> 
</p>
<p class="MsoNormal" style="text-indent:2em;">
	<br />
</p>

		</div>
</div>{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}