{dede:field name='keywords'}HTM2-SWM.12脉冲延时时间继电器{/dede:field}
{dede:field name='description'}HTM2-SWM.12时间继电器是悍客电气（上海）有限公司研制的拥有自主知识产权的脉冲延时继电器，其外观与性能比肩ABB、西门子、施耐德等国际品牌企业产品，是进口脉冲延时时间继电器的理想替代产品！{/dede:field}
{dede:field name='title'}HTM2-SWM.12脉冲延时时间继电器上线_悍客电气（上海）有限公司{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
