<?php
$z[0]=Array("global","",133,165);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",287,319);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",440,472);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",593,625);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("channelartlist","\r\n      <div class=\"help_list wow fadeInUp\" >\r\n        <div class=\"help_top\"><h3>{dede:field name='typename'/}</h3><span></span></div>\r\n        <ul>\r\n          {dede:channel type='son' noself='yes'}\r\n          <li><a href='[field:typeurl/]' title=\"[field:typename/]\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n        </ul>\r\n      </div>\r\n      ",845,1260);
$z[4][4]['typeid']="1,2,3";
$z[5]=Array("global","",1453,1475);
$z[5][4]['name']="cfg_tel";
$z[6]=Array("global","",1587,1619);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("flink","  [field:link /]  ",1880,1958);
$z[7][4]['titlelen']="20";
$z[7][4]['row']="20";
$z[7][4]['type']="text";

?>