<?php
$z[0]=Array("include","",18,53);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",275,304);
$z[1][4]['name']="position";
$z[2]=Array("include","",346,381);
$z[2][4]['filename']="left.htm";
$z[3]=Array("field","",464,492);
$z[3][4]['name']="typeurl";
$z[4]=Array("field","",494,517);
$z[4][4]['name']="seotitle";
$z[5]=Array("field","",569,590);
$z[5][4]['name']="content";
$z[6]=Array("include","",2034,2069);
$z[6][4]['filename']="foot.htm";

?>