<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",280,309);
$z[1][4]['name']="position";
$z[2]=Array("include","",378,413);
$z[2][4]['filename']="left.htm";
$z[3]=Array("field","",486,514);
$z[3][4]['name']="typeurl";
$z[4]=Array("field","",516,545);
$z[4][4]['name']="typename";
$z[5]=Array("list","\r\n            <div class=\"art_list wow fadeInUp\">\r\n              <div class=\"art_img\"><a href='[field:arcurl/]' target=\"_blank\"><img src='[field:picname/]'/></a></div>\r\n              <div class=\"art_right\">\r\n                <div class=\"art_title\"><a href='[field:arcurl/]' >[field:title/]</a></div>\r\n                <div class=\"art_author\"><span>来源：[field:source/]</span><span>作者：[field:writer/]</span> <span>日期：[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></div>\r\n                <div class=\"art_des\">[field:description function=\"cn_substr(@me,300)\"/]...</div>\r\n                <div class='art_more'><a href='[field:arcurl/]' target=\"_blank\">查看更多>></a></div>\r\n              </div>\r\n            </div>\r\n            ",661,1435);
$z[5][4]['pagesize']="6";
$z[6]=Array("pagelist","",1539,1605);
$z[6][4]['listitem']="index,end,pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",1706,1741);
$z[7][4]['filename']="foot.htm";

?>