<?php
$z[0]=Array("field","",306,325);
$z[0][4]['name']="title";
$z[1]=Array("global","",326,352);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",393,422);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",462,521);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1121,1156);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n          <li class=\"l1\"> <a href=\"[field:typelink/]\" id=\"left[field:global.autoindex/]\">\r\n            <div class=\"l_abs\"><img src=\"/skin/images/join_img2.png\" width=\"8\" height=\"30\"></div>\r\n            <div class=\"c_abs\">[field:typename/]</div>\r\n            <div class=\"r_abs\"><img src=\"/skin/images/join_img2.png\" width=\"8\" height=\"30\"></div>\r\n            </a> </li>\r\n          ",1616,2401);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li class='l1'><a href='~typelink~' class='hover'> <div class='l_abs'><img src='/skin/images/join_img2.png' width='8' height='30'></div> <div class='c_abs'>~typename~</div> <div class='r_abs'><img src='/skin/images/join_img2.png' width='8' height='30'></div> </a> </li>";
$z[6]=Array("channel","\r\n            <li class=\"l1\"> <a href=\"[field:typelink/]\" id=\"left[field:global.autoindex/]\">\r\n              <div class=\"l_abs\"><img src=\"/skin/images/join_img2.png\" width=\"8\" height=\"30\"></div>\r\n              <div class=\"c_abs\">[field:typename/]</div>\r\n              <div class=\"r_abs\"><img src=\"/skin/images/join_img2.png\" width=\"8\" height=\"30\"></div>\r\n              </a> </li>\r\n            ",3036,3845);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='l1'><a href='~typelink~' class='hover'> <div class='l_abs'><img src='/skin/images/join_img2.png' width='8' height='30'></div> <div class='c_abs'>~typename~</div> <div class='r_abs'><img src='/skin/images/join_img2.png' width='8' height='30'></div> </a> </li>";
$z[7]=Array("channel","\r\n        <li class=\"l1\"> <a href=\"[field:typelink/]\" id=\"left[field:global.autoindex/]\">\r\n          <div class=\"l_abs\"><img src=\"/skin/images/join_img2.png\" width=\"8\" height=\"30\"></div>\r\n          <div class=\"c_abs\">[field:typename/]</div>\r\n          <div class=\"r_abs\"><img src=\"/skin/images/join_img2.png\" width=\"8\" height=\"30\"></div>\r\n          </a> </li>\r\n        ",4575,5336);
$z[7][4]['type']="son";
$z[7][4]['currentstyle']="<li class='l1'><a href='~typelink~' class='hover'> <div class='l_abs'><img src='/skin/images/join_img2.png' width='8' height='30'></div> <div class='c_abs'>~typename~</div> <div class='r_abs'><img src='/skin/images/join_img2.png' width='8' height='30'></div> </a> </li>";
$z[8]=Array("field","",5793,5815);
$z[8][4]['name']="typename";
$z[9]=Array("field","",5890,5913);
$z[9][4]['name']="seotitle";
$z[10]=Array("field","",6285,6306);
$z[10][4]['name']="content";
$z[11]=Array("include","",6451,6488);
$z[11][4]['filename']="footer.htm";

?>