<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",259,288);
$z[1][4]['name']="position";
$z[2]=Array("include","",357,392);
$z[2][4]['filename']="left.htm";
$z[3]=Array("field","",465,493);
$z[3][4]['name']="typeurl";
$z[4]=Array("field","",511,540);
$z[4][4]['name']="typename";
$z[5]=Array("list","\r\n            <div class=\"pro_list wow fadeInUp\" data-wow-delay=\".2s\">\r\n              <div class=\"pro_item pro_list2\">\r\n                <div class=\"pro_item_img\" style=\"background-image:url([field:picname/]);\"></div>\r\n                <div class=\"pro_item_title\">\r\n                  <h3><a href='[field:arcurl/]' target=\"_blank\">[field:title/]</a></h3>\r\n                  <h4>[field:description function=\"cn_substr(@me,60)\"/]...</h4>\r\n                </div>\r\n              </div>\r\n            </div>\r\n            ",656,1205);
$z[5][4]['pagesize']="8";
$z[6]=Array("pagelist","",1286,1352);
$z[6][4]['listitem']="index,end,pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",1468,1503);
$z[7][4]['filename']="foot.htm";

?>